#makefile maybe used

SRC = main.py
SUPPLEMENTARY = bool_func.py
BOOL_EXP = test.txt

CUR_DIR = $(shell pwd)

.phony: all build clean 

all: clean build

clean:
	rm -rf __pycache__

build:
	python3 $(SRC) 